version = 1

# Config files etc.
[[annotations]]
path = [
    ".github/workflows/rust.yml",
    ".gitignore",
    "Cargo.lock",
    "REUSE.toml",
]
precedence = "override"
SPDX-FileCopyrightText = "2026 The mwifiex_nl80211_test_mode authors"
SPDX-License-Identifier = "CC0-1.0"

# The AUTHORS file itself
[[annotations]]
path = [
    "AUTHORS",
]
precedence = "override"
SPDX-FileCopyrightText = "2026 mwifiex_nl80211_test_mode authors"
SPDX-License-Identifier = "CC0-1.0"
